export const seedSongs = [
  {
    "title": "Goodness of God",
    "artist": "Bethel Music",
    "originalKey": "G",
    "bpm": 63,
    "timeSignature": "4/4",
    "tags": ["Monospace", "Worship", "Thanksgiving", "Bethel"],
    "lyrics": "Verse 1\nC                 \nI love You Lord\n               F                   C\nOh Your mercy never fails me\nG/B        Am\nAll my days\n              F                        G\nI've been held in Your hands\n                                  Am                     F\nFrom the moment that I wake up\n            C    G/B   Am\nUntil I lay my head\nF                              G                   C\nI will sing of the goodness of God\n\nChorus\nF                                                                C\nAll my life You have been faithful\nF                                                                C        G\nAll my life You have been so, so good\nF                                                                C  G/B  Am\nWith every breath that I am able\nF                              G                   C\nI will sing of the goodness of God\n\nVerse 2\nC\nI love Your voice\n                  F                                C\nYou have led me through the fire\n     G/B       Am\nIn darkest nights\n             F                         G\nYou are close like no other\n                             Am               F\nI've known You as a father\n                             C   G/B  Am\nI've known You as a friend\nF                                 G                  C\nI have lived in the goodness of God\n\nBridge\nC/E                                  F\nYour goodness is running after\nG                                       C\nIt's running after me\nC/E                                  F\nYour goodness is running after\nG                                       C\nIt's running after me\nC/E                                                   F\nWith my life laid down, I'm surrendered now\nG                                  Am\nI give You everything\nC/E                                  F\nYour goodness is running after\nG                                       C\nIt's running after me"
  },
  {
    "title": "Way Maker",
    "artist": "Sinach",
    "originalKey": "E",
    "bpm": 68,
    "timeSignature": "4/4",
    "tags": ["Monospace", "Worship", "Faith", "Miracles"],
    "lyrics": "Verse 1\nA\nYou are here, moving in our midst\nE                                                B\nI worship You, I worship You\nC#m                                      A\nYou are here, working in this place\nE                                                B\nI worship You, I worship You\n\nChorus\n                                   A\nYou are Way Maker, Miracle Worker, Promise Keeper\nE\nLight in the darkness\nB                                          C#m\nMy God, that is who You are\n\nVerse 2\nA\nYou are here, touching every heart\nE                                                B\nI worship You, I worship You\nC#m                                      A\nYou are here, healing every heart\nE                                                B\nI worship You, I worship You\n\nVerse 3\nA\nYou are here, turning lives around\nE                                                B\nI worship You, I worship You\nC#m                                      A\nYou are here, mending every heart\nE                                                B\nI worship You, I worship You\n\nBridge\nA\nEven when I don't see it, You're working\nE\nEven when I don't feel it, You're working\nB\nYou never stop, You never stop working\nC#m\nYou never stop, You never stop working"
  },
  {
    "title": "10,000 Reasons (Bless The Lord)",
    "artist": "Matt Redman",
    "originalKey": "G",
    "bpm": 73,
    "timeSignature": "4/4",
    "tags": ["Praise", "Worship", "Morning"],
    "lyrics": "Chorus\n                       C             G\nBless the Lord, O my soul\nD/F# Em\nO my soul\nC                        G          D\nWorship His holy name\n                          C           Em\nSing like never before\nC   D   Em\nO my soul\nI'll worship Your holy name\n\nVerse 1\n       C             G              D             Em\nThe sun comes up, it's a new day dawning\nC                   G                       D            Em\nIt's time to sing Your song again\n     C                  G                         D                       Em\nWhatever may pass, and whatever lies before me\nC                    G                         D                  G\nLet me be singing when the evening comes\n\nVerse 2\n             C           G                   D              Em\nYou're rich in love, and You're slow to anger\n         C               G                   D                 Em\nYour name is great, and Your heart is kind\n        C               G                        D          Em\nFor all Your goodness I will keep on singing\nC                           G                       D               G\nTen thousand reasons for my heart to find\n\nVerse 3\n          C           G                        D               Em\nAnd on that day when my strength is failing\n        C             G                        D               Em\nThe end draws near and my time has come\n C               G                           D               Em\nStill my soul will sing Your praise unending\nC                           G                           D              G\nTen thousand years and then forevermore"
  },
  {
    "title": "Oceans (Where Feet May Fail)",
    "artist": "Hillsong United",
    "originalKey": "D",
    "bpm": 64,
    "timeSignature": "4/4",
    "tags": ["Monospace", "Worship", "Faith", "Trust"],
    "lyrics": "Verse 1\nBm                                   A/C#     D\nYou call me out upon the waters\n                               A                             G\nThe great unknown where feet may fail\nBm                                       A/C#     D\nAnd there I find You in the mystery\n                               A                             G\nIn oceans deep my faith will stand\n\nChorus\nG                       D                      A\nAnd I will call upon Your name\nG                       D                           A\nAnd keep my eyes above the waves\n                                     G\nWhen oceans rise\n                                 D                          A\nMy soul will rest in Your embrace\n                                 G            A         Bm\nFor I am Yours and You are mine\n\nVerse 2\nBm                                                   A/C#     D\nYour grace abounds in deepest waters\n                                        A                          G\nYour sovereign hand will be my guide\nBm                                                        A/C#     D\nWhere feet may fail and fear surrounds me\n                                               A                                  G\nYou've never failed and You won't start now\n\nBridge\nBm                                           G\nSpirit lead me where my trust is without borders\n                                  D\nLet me walk upon the waters\n                                   A\nWherever You would call me\nBm                                          G\nTake me deeper than my feet could ever wander\n                                                D\nAnd my faith will be made stronger\n                                            A\nIn the presence of my Savior"
  },
  {
    "title": "King of Kings",
    "artist": "Hillsong Worship",
    "originalKey": "D",
    "bpm": 68,
    "timeSignature": "4/4",
    "tags": ["Monospace", "Worship", "Gospel", "Easter"],
    "lyrics": "Verse 1\nD/F#                          G\nIn the darkness we were waiting\nA                                     D\nWithout hope without light\nD/F#                          G\nTill from Heaven You came running\nA                                     D\nThere was mercy in Your eyes\nD/F#                          G\nTo fulfill the law and prophets\nA                                     D\nTo a virgin came the Word\nD/F#                          G\nFrom a throne of endless glory\nA                                     D\nTo a cradle in the dirt\n\nChorus\nD\nPraise the Father\nG\nPraise the Son\nBm                        A\nPraise the Spirit three in one\nD\nGod of Glory\nG\nMajesty\nBm                        A                 D\nPraise forever to the King of Kings\n\nVerse 2\nD/F#                          G\nTo reveal the kingdom coming\nA                                     D\nAnd to reconcile the lost\nD/F#                          G\nTo redeem the whole creation\nA                                     D\nYou did not despise the cross\nD/F#                          G\nFor even in Your suffering\nA                                     D\nYou saw to the other side\nD/F#                          G\nKnowing this was our salvation\nA                                     D\nJesus for our sake You died\n\nVerse 3\nD/F#                          G\nAnd the morning that You rose\nA                                     D\nAll of heaven held its breath\nD/F#                          G\nTill that stone was moved for good\nA                                     D\nFor the Lamb had conquered death\nD/F#                          G\nAnd the dead rose from their tombs\nA                                     D\nAnd the angels stood in awe\nD/F#                          G\nFor the souls of all who'd come\nA                                     D\nTo the Father are restored\n\nVerse 4\nD/F#                          G\nAnd the Church of Christ was born\nA                                     D\nThen the Spirit lit the flame\nD/F#                          G\nNow this Gospel truth of old\nA                                     D\nShall not kneel shall not faint\nD/F#                          G\nBy His blood and in His Name\nA                                     D\nIn His freedom I am free\nD/F#                          G\nFor the love of Jesus Christ\nA                                     D\nWho has resurrected me"
  },
  {
    "title": "What A Beautiful Name",
    "artist": "Hillsong Worship",
    "originalKey": "D",
    "bpm": 68,
    "timeSignature": "4/4",
    "tags": ["Monospace", "Worship", "Jesus", "Praise"],
    "lyrics": "Verse 1\nD\nYou were the Word at the beginning\nG                      Bm                 A\nOne with God the Lord Most High\nBm                A/C#             D\nYour hidden glory in creation\nG                   Bm                 A\nNow revealed in You our Christ\n\nChorus 1\n                                               D\nWhat a beautiful Name it is\n                                               A\nWhat a beautiful Name it is\n                   Bm                   A                     G\nThe Name of Jesus Christ my King\n                                               D/F#\nWhat a beautiful Name it is\n                                         A\nNothing compares to this\n                                               Bm\nWhat a beautiful Name it is\n          A                 G\nThe Name of Jesus\n\nVerse 2\nD\nYou didn't want heaven without us\nG                     Bm                      A\nSo Jesus You brought heaven down\nBm                   A/C#                  D\nMy sin was great Your love was greater\nG                    Bm               A\nWhat could separate us now\n\nChorus 2\n                                               D\nWhat a wonderful Name it is\n                                               A\nWhat a wonderful Name it is\n                   Bm                   A                     G\nThe Name of Jesus Christ my King\n                                               D/F#\nWhat a wonderful Name it is\n                                         A\nNothing compares to this\n                                               Bm\nWhat a wonderful Name it is\n          A                 G\nThe Name of Jesus\n\nBridge\nG                                               A\nDeath could not hold You, the veil tore before You\nBm                                           F#m\nYou silence the boast of sin and grave\nG                                                A\nThe heavens are roaring the praise of Your glory\nBm                                      A\nFor You are raised to life again\nG                                                A\nYou have no rival, You have no equal\nBm                                      F#m\nNow and forever God You reign\nG                                                A\nYours is the kingdom, Yours is the glory\nBm                                      A\nYours is the Name above all names\n\nChorus 3\n                                               D\nWhat a powerful Name it is\n                                               A\nWhat a powerful Name it is\n                   Bm                   A                     G\nThe Name of Jesus Christ my King\n                                               D/F#\nWhat a powerful Name it is\n                                         A\nNothing can stand against\n                                               Bm\nWhat a powerful Name it is\n          A                 G\nThe Name of Jesus"
  },
  {
    "title": "Build My Life",
    "artist": "Housefires",
    "originalKey": "G",
    "bpm": 70,
    "timeSignature": "4/4",
    "tags": ["Monospace", "Worship", "Surrender", "Dedication"],
    "lyrics": "Verse 1\nG                                             C\nWorthy of every song we could ever sing\nG/B                                           C\nWorthy of all the praise we could ever bring\nG                                             C\nWorthy of every breath we could ever breathe\nG/B                                           C\nWe live for You\n\nVerse 2\nG                                             C\nJesus the name above every other name\nG/B                                           C\nJesus the only one who could ever save\nG                                             C\nWorthy of every breath we could ever breathe\nG/B                                           C\nWe live for You, We live for You\n\nChorus\nC                                   Am\nHoly, there is no one like You\n                                  G\nThere is none beside You\n                              Em\nOpen up my eyes in wonder\nC                                                  Am\nShow me who You are and fill me\n                                      G\nWith Your heart and lead me\n                                            Em\nIn Your love to those around me\n\nBridge\nC                                   D\nI will build my life upon Your love\nEm                                 G/B\nIt is a firm foundation\nC                                   D\nI will put my trust in You alone\nEm                                 G/B\nAnd I will not be shaken"
  }
];
